/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kos_pria;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author DFN COMPUTER
 */
public class penyewa extends javax.swing.JFrame {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    private Connection Con;
    private Statement stm;
    public Statement stt;
    public java.sql.Connection con;
    private TableColumn column;
    String temp_idpenyewa="";
    
    /**
     * Creates new form penyewa
     */
    public penyewa() {
        initComponents();
        String[] judul={"ID PENYEWA","NAMA PENYEWA","ALAMAT","USIA","NO HP","PROFESI"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        tampilkan_data();
        penomoran_otomatis();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a_profesi = new javax.swing.JTextField();
        a_idpenyewa = new javax.swing.JTextField();
        a_alamat = new javax.swing.JTextField();
        a_usia = new javax.swing.JTextField();
        a_no = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        a_namapenyewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Profesi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PENYEWA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID Penyewa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Usia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Nomer Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        a_profesi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_profesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_profesiActionPerformed(evt);
            }
        });
        getContentPane().add(a_profesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 150, -1));

        a_idpenyewa.setEditable(false);
        a_idpenyewa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_idpenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idpenyewaActionPerformed(evt);
            }
        });
        getContentPane().add(a_idpenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, -1));

        a_alamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(a_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 150, -1));

        a_usia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_usiaActionPerformed(evt);
            }
        });
        getContentPane().add(a_usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, -1));

        a_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_noActionPerformed(evt);
            }
        });
        getContentPane().add(a_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 90, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 90, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 90, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 90, 30));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 660, 130));

        a_namapenyewa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_namapenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_namapenyewaActionPerformed(evt);
            }
        });
        getContentPane().add(a_namapenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Nama Penyewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/kost_2.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 570));

        setSize(new java.awt.Dimension(829, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a_profesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_profesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_profesiActionPerformed

    private void a_idpenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idpenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_idpenyewaActionPerformed

    private void a_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_alamatActionPerformed

    private void a_usiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_usiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_usiaActionPerformed

    private void a_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_noActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
a_idpenyewa.setText("");
a_alamat.setText("");
a_usia.setText("");
a_namapenyewa.setText("");
a_no.setText("");
a_profesi.setText("");
penomoran_otomatis();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void penomoran_otomatis() {
        int no_idpenyewa=0;
        String temp_idpenyewa="";
        try {
            koneksi();
            String sql = "select id_penyewa from penyewa order by id_penyewa desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_idpenyewa = res.getString(1);                
                String nomor_blkg = temp_idpenyewa.substring(2,4);
                no_idpenyewa=Integer.parseInt(nomor_blkg);
            }
                        
            no_idpenyewa++;
            String nilai=String.valueOf(no_idpenyewa);                      
            if(nilai.length()==1){
                a_idpenyewa.setText("P00"+no_idpenyewa);
            }else
            if(nilai.length()==2){
                a_idpenyewa.setText("P0"+no_idpenyewa);
            }else
            if(nilai.length()==3){
                a_idpenyewa.setText("P"+no_idpenyewa);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
     private void tampilkan_data() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM penyewa ORDER BY id_penyewa");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
     private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
String id = a_idpenyewa.getText();
String nama = a_namapenyewa.getText();
String alamat = a_alamat.getText();
String usia = a_usia.getText();
String no = a_no.getText();
String profesi = a_profesi.getText();



{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into penyewa values('"+id+"','"+nama+"','"+alamat+"','"+usia+"','"+no+"','"+profesi+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
a_idpenyewa.setText("");
a_alamat.setText("");
a_usia.setText("");
a_namapenyewa.setText("");
a_no.setText("");
a_profesi.setText("");
penomoran_otomatis();
koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
finally {
tampilkan_data();

}
    }                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(a_idpenyewa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Penyewa ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM penyewa where id_penyewa='"+a_idpenyewa.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }
                
            }
a_idpenyewa.setText("");
a_alamat.setText("");
a_usia.setText("");
a_namapenyewa.setText("");
a_no.setText("");
a_profesi.setText("");
penomoran_otomatis();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
String id = a_idpenyewa.getText();
String nama = a_namapenyewa.getText();
String alamat = a_alamat.getText();
String usia = a_usia.getText();
String no = a_no.getText();
String profesi = a_profesi.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
String sql="UPDATE penyewa SET id_penyewa='"+id+"',nama='"+nama+"',alamat='"+alamat+"',usia='"+usia+"',no_hp='"+no+"',profesi='"+profesi+"' WHERE id_penyewa LIKE '"+id+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil di UPDATE..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}finally{
tampilkan_data();
a_idpenyewa.setText("");
a_alamat.setText("");
a_usia.setText("");
a_namapenyewa.setText("");
a_no.setText("");
a_profesi.setText("");
penomoran_otomatis();
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void a_namapenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_namapenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_namapenyewaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        a_idpenyewa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        a_namapenyewa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        a_alamat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        a_usia.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        a_no.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        a_profesi.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
                        
        temp_idpenyewa = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_alamat;
    private javax.swing.JTextField a_idpenyewa;
    private javax.swing.JTextField a_namapenyewa;
    private javax.swing.JTextField a_no;
    private javax.swing.JTextField a_profesi;
    private javax.swing.JTextField a_usia;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
