/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kos_pria;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class TRANSAKSI extends javax.swing.JFrame {
private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    private Connection Con;
    private Statement stm;
    public Statement stt;
    public java.sql.Connection con;
    private TableColumn column;
    String temp_transaksi="";
    
    public int harga, jml, total, bayar, kurang, kembalian;
    /**
     * Creates new form TRANSAKSI
     */
    public TRANSAKSI() {
        initComponents();
        String[] judul={"KODE TRANSAKSI","ID PENYEWA","NAMA PENYEWA","NO HP","JENIS KAMAR","HARGA","NOMOR KAMAR","JUMLAH TAHUN","TOTAL","BAYAR","KEKURANGAN","KEMBALIAN"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        tampil_idpenyewa();
        tampil_jeniskamar();
        tampilkan_data();
        penomoran_otomatis();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ulang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a_idt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        a_harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        a_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        a_nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a_jml = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        a_total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        a_bayar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        a_kurang = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        del = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        a_not = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        a_idp = new javax.swing.JComboBox<>();
        a_jenis = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        a_kembali = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ulang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ulang.setText("ULANG");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });
        getContentPane().add(ulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 80, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID Transaksi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        a_idt.setEditable(false);
        a_idt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_idt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idtActionPerformed(evt);
            }
        });
        getContentPane().add(a_idt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Kamar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Harga Kamar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        a_harga.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(a_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 150, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Nomor Kamar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        a_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_noActionPerformed(evt);
            }
        });
        getContentPane().add(a_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 50, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Id Penyewa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Nama Penyewa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        a_nama.setEditable(false);
        a_nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_namaActionPerformed(evt);
            }
        });
        getContentPane().add(a_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Nomer Telefon");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Jumlah Tahun");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        a_jml.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_jmlActionPerformed(evt);
            }
        });
        getContentPane().add(a_jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 50, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        a_total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_totalActionPerformed(evt);
            }
        });
        getContentPane().add(a_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 150, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Bayar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        a_bayar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(a_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 130, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Kekurangan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        a_kurang.setEditable(false);
        a_kurang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_kurangActionPerformed(evt);
            }
        });
        getContentPane().add(a_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 90, 30));

        simpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 90, 30));

        del.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 90, 30));

        edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 90, 30));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 90, 30));

        a_not.setEditable(false);
        a_not.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_notActionPerformed(evt);
            }
        });
        getContentPane().add(a_not, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 780, 120));

        a_idp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH ID PENYEWA --" }));
        a_idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idpActionPerformed(evt);
            }
        });
        getContentPane().add(a_idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, -1));

        a_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH JENIS KAMAR --" }));
        a_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_jenisActionPerformed(evt);
            }
        });
        getContentPane().add(a_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, -1));

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Kembalian");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        a_kembali.setEditable(false);
        a_kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(a_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 150, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/kost_2.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        setSize(new java.awt.Dimension(857, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void penomoran_otomatis() {
        int no_transaksi=0;
        String temp_transaksi="";
        try {
            koneksi();
            String sql = "select id_transaksi from transaksi order by id_transaksi desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_transaksi = res.getString(1);                
                String nomor_blkg = temp_transaksi.substring(3,5);
                no_transaksi=Integer.parseInt(nomor_blkg);
            }
                        
            no_transaksi++;
            String nilai=String.valueOf(no_transaksi);                      
            if(nilai.length()==1){
                a_idt.setText("TR00"+no_transaksi);
            }else
            if(nilai.length()==2){
                a_idt.setText("TR0"+no_transaksi);
            }else
            if(nilai.length()==3){
                a_idt.setText("TR"+no_transaksi);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }

     private void tampilkan_data() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM transaksi ORDER BY id_transaksi");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7),re.getString(8),re.getString(9),re.getString(10),re.getString(11),re.getString(12)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
     private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
     private void tampil_idpenyewa() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM penyewa ORDER BY id_penyewa ASC");
            while(re.next()){
                a_idp.addItem(re.getString("id_penyewa"));
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Id penyewa !");
        }
    }
     
     private void tampil_jeniskamar() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM kamar ORDER BY jenis_kamar ASC");
            while(re.next()){
                a_jenis.addItem(re.getString("jenis_kamar"));
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Kode Jenis Kamrar !");
        }
    }
    private void a_idtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_idtActionPerformed

    private void a_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_hargaActionPerformed

    private void a_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_noActionPerformed

    private void a_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_namaActionPerformed

    private void a_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_jmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_jmlActionPerformed

    private void a_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_totalActionPerformed

    private void a_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_bayarActionPerformed

    private void a_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_kurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_kurangActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        a_idt.setText("");
        a_idp.setSelectedItem("-- PILIH ID PENYEWA --");
        a_nama.setText("");
        a_not.setText("");
        a_jenis.setSelectedItem("-- PILIH JENIS KAMAR --");
        a_harga.setText("");
        a_no.setText("");
        a_jml.setText("");
        a_total.setText("");
        a_bayar.setText("");
        a_kurang.setText("");
        a_kembali.setText("");
        penomoran_otomatis();
    }//GEN-LAST:event_clearActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String id = a_idt.getText();
        String idp = (String) a_idp.getSelectedItem();
        String nama = a_nama.getText();
        String not = a_not.getText();
        String jenis = (String) a_jenis.getSelectedItem();
        String harga = a_harga.getText();
        String no = a_no.getText();
        String jml = a_jml.getText();
        String total = a_total.getText();
        String bayar = a_bayar.getText();
        String kurang = a_kurang.getText();
        String kembali = a_kembali.getText();

        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
                Statement statement = (Statement) koneksi.createStatement();
                String sql="insert into transaksi values('"+id+"','"+idp+"','"+nama+"','"+not+"','"+jenis+"','"+harga+"','"+no+"','"+jml+"','"+total+"','"+bayar+"','"+kurang+"','"+kembali+"')";
                int executeUpdate = statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);

                koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
                //System.err.println("Exception: "+e.getMessage());
            }
            finally {
                tampilkan_data();
        a_idt.setText("");
        a_idp.setSelectedItem("-- PILIH ID PENYEWA --");
        a_nama.setText("");
        a_not.setText("");
        a_jenis.setSelectedItem("-- PILIH JENIS KAMAR --");
        a_harga.setText("");
        a_no.setText("");
        a_jml.setText("");
        a_total.setText("");
        a_bayar.setText("");
        a_kurang.setText("");
        a_kembali.setText("");
                penomoran_otomatis();
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        if(a_idt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Transaksi ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/kos_pria","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM transaksi where id_transaksi='"+a_idt.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }

            }
        a_idt.setText("");
        a_idp.setSelectedItem("-- PILIH ID PENYEWA --");
        a_nama.setText("");
        a_not.setText("");
        a_jenis.setSelectedItem("-- PILIH JENIS KAMAR --");
        a_harga.setText("");
        a_no.setText("");
        a_jml.setText("");
        a_total.setText("");
        a_bayar.setText("");
        a_kurang.setText("");
        a_kembali.setText("");
            penomoran_otomatis();

        }
    }//GEN-LAST:event_delActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String id = a_idt.getText();
        String idp = (String) a_idp.getSelectedItem();
        String nama = a_nama.getText();
        String not = a_not.getText();
        String jenis = (String) a_jenis.getSelectedItem();
        String harga = a_harga.getText();
        String no = a_no.getText();
        String jml = a_jml.getText();
        String total = a_total.getText();
        String bayar = a_bayar.getText();
        String kurang = a_kurang.getText();
        String kembali = a_kembali.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
            String sql="UPDATE transaksi SET id_transaksi='"+id+"',id_penyewa='"+idp+"',nama_penyewa='"+nama+"',no_hp='"+not+"',jenis_kamar='"+jenis+"',harga_kamar='"+harga+"',nomor_kamar='"+no+"',jml_tahun='"+jml+"',total='"+total+"',bayar='"+bayar+"',kekurangan='"+kurang+"',kembalian='"+kembali+"' WHERE id_transaksi LIKE '"+id+"'";
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil di UPDATE..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }finally{
            tampilkan_data();
        a_idt.setText("");
        a_idp.setSelectedItem("-- PILIH ID PENYEWA --");
        a_nama.setText("");
        a_not.setText("");
        a_jenis.setSelectedItem("-- PILIH JENIS KAMAR --");
        a_harga.setText("");
        a_no.setText("");
        a_jml.setText("");
        a_total.setText("");
        a_bayar.setText("");
        a_kurang.setText("");
        a_kembali.setText("");
            penomoran_otomatis();
        }
    }//GEN-LAST:event_editActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void a_notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_notActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_notActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         a_idt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        a_idp.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        a_nama.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        a_not.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        a_jenis.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        a_harga.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        a_no.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        a_jml.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        a_total.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        a_bayar.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        a_kurang.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        a_kembali.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
                        
        temp_transaksi = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    private void a_idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idpActionPerformed
         // TODO add your handling code here:
        a_nama.setText(null);
        a_not.setText(null);
         String idpenyewa = (String) a_idp.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
String sql="SELECT * FROM penyewa WHERE id_penyewa like '"+idpenyewa+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
a_nama.setText(rs.getString(2));
a_not.setText(rs.getString(5));
}

statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }//GEN-LAST:event_a_idpActionPerformed

    private void a_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_jenisActionPerformed
        // TODO add your handling code here:
        a_harga.setText(null);
         String jenis = (String) a_jenis.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/kos_pria", "root", "");
com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
String sql="SELECT * FROM kamar WHERE jenis_kamar like '"+jenis+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
a_harga.setText(rs.getString(3));

}

statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }//GEN-LAST:event_a_jenisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(a_harga.getText());
            jml = Integer.parseInt(a_jml.getText());
            total = harga * jml;

            a_total.setText(total + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            total = Integer.parseInt(a_total.getText());
            bayar = Integer.parseInt(a_bayar.getText());
            if(bayar > total) {
              a_kurang.setText("0");
              kembalian = bayar - total;
            }
            else if(total > bayar){
              a_kembali.setText("0");
              kurang = total - bayar;
            }
            
            a_kembali.setText(kembalian + "");
            a_kurang.setText(kurang + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void a_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_kembaliActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        // TODO add your handling code here:
        a_bayar.setText("");
        a_kurang.setText("");
        a_kembali.setText("");
    }//GEN-LAST:event_ulangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRANSAKSI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_bayar;
    private javax.swing.JTextField a_harga;
    private javax.swing.JComboBox<String> a_idp;
    private javax.swing.JTextField a_idt;
    private javax.swing.JComboBox<String> a_jenis;
    private javax.swing.JTextField a_jml;
    private javax.swing.JTextField a_kembali;
    private javax.swing.JTextField a_kurang;
    private javax.swing.JTextField a_nama;
    private javax.swing.JTextField a_no;
    private javax.swing.JTextField a_not;
    private javax.swing.JTextField a_total;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
